# Generated by Django 6.0.2 on 2026-03-03 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "correo_electronico",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anotacion", models.TextField(verbose_name="Anotacion")),
                ("fecha", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumnos.alumno"
                    ),
                ),
            ],
        ),
    ]
